version: 2.1

orbs:
  netflex: netflex/netflex-deploy@2.0.6

jobs:
  tests:
    docker:
      - image: circleci/php:7.2
    steps:
      - netflex/pull
      - netflex/composer
      - run:
          name: PHPUnit
          command: cd ~/project && composer run-script tests

workflows:
  version: 2
  deployment:
    jobs:
      - tests
